sonar.projectKey=Daniboigg_red-alimentos-solidarios
sonar.organization=daniboigg
sonar.sources=backend/src
sonar.tests=backend/tests
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.coverage.exclusions=backend/tests/**,backend/src/server.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.ts
sonar.sourceEncoding=UTF-8