sonar.projectKey=Daniboigg_red-alimentos-solidarios
sonar.organization=Daniboigg
sonar.sources=backend/src
sonar.tests=backend/tests
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**